apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shenali-SJ/app-tmwEvWCLbQ3HzD8PZGM6ug-helm.git
    targetRevision: main
    path: ./
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
